### ISSUE TITLE
Add Linked List to structures-wiz

### ISSUE THREAD

**Issue by thisisprasad** [harsh07bharvada/structures-wiz#1]
Hi Harsh,
I would like to request for the addition of Linked List data structure module in javascript for structures-wiz package. The Linked List module shall consist of (i)Singly (ii) Doubly and (iii) Circular linked lists.
The linked list data structure provides an efficient way to implement Stacks, Queues, etc as of these data structures memory changes dynamically during the runtime of an application/program.

**Comment by thisisprasad** [comment]
I would like to work on this issue by starting with the implementation of Singly linked list.

**Comment by harsh07bharvada** [comment]
> Hi Harshad,
> I would like to request for the addition of Linked List data structure module in javascript for structures-wiz package. The Linked List module shall consist of (i)Singly (ii) Doubly and (iii) Circular linked lists.
> The linked list data structure provides an efficient way to implement Stacks, Queues, etc as of these data structures memory changes dynamically during the runtime of an application/program.

Hi Prasad,
Arrays in JavaScript are objects under the hood unlike other languages, thus there is not much difference between the implementation of Stacks and Queues using Linked Lists or using Arrays.

**Comment by harsh07bharvada** [comment]
> I would like to work on this issue by starting with the implementation of Singly linked list.

Feel free to fork and create a Pull Request. If it aligns with my vision I will definitely merge the same. Please refer to the current PriorityQueue Class to refer for code structure and format for better chances of acceptance. Kindly try to optimise the approach with a clean code. Happy Coding!

**Comment by harsh07bharvada** [comment]
Addition complete so closing this issue.
